### ISSUE TITLE
message-mode is always set to English

### ISSUE THREAD

**Issue by semente** [nschum/auto-dictionary-mode#11]
Looks like my message-mode is always set to use English dictionary. Is there any work around to fix this?

**Comment by semente** [comment]
Based on a fix for ERC I found in a [EmacsWiki page](http://www.emacswiki.org/emacs/AutoDictionaryMode), I end up with this solution:

```emacs-lisp
(defun message-flyspell-predicate ()
      (let ((face (get-text-property (point) 'face)))
        (not (memq (if (listp face) (car face) face)
                   '(message-notice-face message-timestamp-face
                                         message-nick-default-face message-current-nick-face
                                         message-button message-prompt-face)))))

(put 'message-mode 'flyspell-mode-predicate 'message-flyspell-predicate)
```

May is worth to put in the README file.

**Comment by sten0** [comment]
I have the following set, and detection works correctly
```elisp
(add-hook 'text-mode-hook 'flyspell-mode)
(add-hook 'flyspell-mode-hook '(lambda () (auto-dictionary-mode 1)))
```

If this also works for you, maybe it could be documented?  P.S. I know adding anonymous functions as hooks is bad style ;-)

**Comment by semente** [comment]
Hey @sten0, I'm not using auto-dictionary-mode anymore but I'm pretty sure I had a similar setup. Probably it was a bug in my setup. Thank you
